### ISSUE TITLE
Workflow Parser

### ISSUE THREAD

**Issue by bdehaynin** [ipvm-wg/homestar#75]
### Summary

For the MVP, Workflows will be rendered as JSON and need to be loading, parsed, and then executed---really queued for execution. Eventually, we'll allow for other input formats, and #103 for generating workflow configuration and translation. 

### Goals

- [x] Make sure workflows are convertible to JSON and back.
- [x] Run multiple workflows over CLI.
- [x] Load workflows from CLI `.json` files.

ETA: 2023-08-15
